max_parallel_jobs: 1

barriers:
  - name: barrierA
    jobs: [job4, job5]

jobs:
  - name: job1
    deps: []
  - name: job2
    deps: []
  - name: job3
    deps: [job1, job2]
  - name: job4
    deps: []
    barrier: barrierA
  - name: job5
    deps: [job4]
    barrier: barrierA
  - name: job6
    deps: [job3, job5]
